### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by hypervtechnics**

### CODE REVIEW

**Comment by philvessey** [comment]
Inside GetDepartureTimeFromDeparture the following logic is wrong:

// When hour >= 72 then 2 days should be added
// When hour >= 48 then 1 day should be added
// When hour >= 24 then no days should be added
// When hour < 24 then -1 days should be added

It should be as far as I can see:

// When hour >= 72 then 3 days should be added
// When hour >= 48 then 2 days should be added
// When hour >= 24 then 1 day should be added
// When hour < 24 then no days should be added

Do you agree as its returning no results and debugging looking through methods everything is fine up until this point as no matter what its returning a DateTime always showing yesterdays date.

**Comment by philvessey** [comment]
AddDays(((int) (departureHour / 24)) - 1) - this is the section that is wrong I think as in the case of 3AM today that makes AddDays(-1) when it should be AddDays(0).

**Comment by hypervtechnics** [comment]
I was already wondering about this actually. But maybe I got something wrong there. I fixed that.

**Comment by philvessey** [comment]
ByStop now looks good and returns expected results.

ByTrip has an issue and returns the overall trip twice in one list - I think this is because when GetDepartureTimeFromDeparture runs and its checking tomorrows potential departures - the DateTime for those still comes back as today so it includes them again.

I think this could be an error in my logic - im sure with trip we only need to check today and not yesterday or tomorrow as if a trip goes into tomorrow its hour would be 24 or 25 etc.

**Comment by philvessey** [comment]
In which case we could just check today and set toleranceInHours to be 24 on ByTrip.

EDIT: On second thoughts it should be checking yesterday and today with the toleranceInHours as 12 and then it should return correct - ill test that now.

**Comment by philvessey** [comment]
I can see the issue I think - GetDepartureTimeFromDeparture doesnt take into account the dayOffset - in other words depending on the day offset the calculation is wrong.

// When hour >= 72 then 3 days should be added
// When hour >= 48 then 2 days should be added
// When hour >= 24 then 1 day should be added
// When hour < 24 then no days should be added

This should only apply if the day offset is 0. If dayOffset is -1 then your initial calculation was correct.

Can you modify the method to take this into account? So in full it should be:

// Yesterday (dayOffset = -1)
// When hour >= 72 then 2 days should be added
// When hour >= 48 then 1 day should be added
// When hour >= 24 then no days should be added
// When hour < 24 then -1 days should be added

// Today (dayOffset = 0)
// When hour >= 72 then 3 days should be added
// When hour >= 48 then 2 days should be added
// When hour >= 24 then 1 day should be added
// When hour < 24 then no days should be added

// Tomorrow (dayOffset = 1)
// When hour >= 72 then 4 days should be added
// When hour >= 48 then 3 days should be added
// When hour >= 24 then 2 days should be added
// When hour < 24 then 1 day should be added

**Comment by philvessey** [comment]
So i think this should be AddDays(((int) (departureHour / 24)) + dayOffset)

**Comment by philvessey** [comment]
I have now corrected the method and ByStop and ByTrip are now producing expected results! This is a serious amount of work you have done on this and its appreciated! If you are done with the refactor let me know and I will merge into dev but if you want to do some more before the merge let me know but everything looks good so far.

**Comment by hypervtechnics** [comment]
Does it work now? :D

**Comment by philvessey** [comment]
It sure does :)

**Comment by hypervtechnics** [comment]
Could you test the replacement of DateTime.UtcNow with a custom time? I will implement some options to be more flexible ^^

And do you think it is compliant with your logic if we do not iterate three times (each day) and instead iterate once and check all three days at once? I think this would gain some performance. Don't know about the sorting of the result tho.

Also I will implement another DataStorage property which indicates if the results are sorted properly and if not the library will sort appropiate.

**Comment by philvessey** [comment]
> Could you test the replacement of DateTime.UtcNow with a custom time? I will implement some options to be more flexible ^^

Thinking of DateTime - im not sure if we need to switch to NodaTime or an alternative as the TimeZoneConverter only converts to windows time which is an issue if not running on windows of course. But would be a good idea to add more flexibility.
 
> And do you think it is compliant with your logic if we do not iterate three times (each day) and instead iterate once and check all three days at once? I think this would gain some performance. Don't know about the sorting of the result tho.

It would improve performance for sure but the sorting issue is the only reason I checked three times as otherwise I have no idea how the sort would be correct.

**Comment by hypervtechnics** [comment]
1. And if the user supplies the time in UTC?

2. Okay the sorting issue can be solved easily and save a lot of performance :)

**Comment by philvessey** [comment]
1. The user supplying the time is not the issue - we can do that no problem - the issue is TZConvert.IanaToWindows(timezone) there isnt a method in the current library to convert the IANA time format that GTFS uses to anything other than windows or rails time formats - some reading suggests Nodatime will help with this but I need to look more at it.

2. If you know how to do it then go for it - you want to do it on this branch or shall I merge in this one and start another for that?

**Comment by hypervtechnics** [comment]
I will do it later in this branch :)

**Comment by philvessey** [comment]
Ok - im going to setup an Azure Pipeline so that commits to master trigger builds and uploads to NuGet.

**Comment by philvessey** [comment]
CI / CD is ready for commits to master - it will build in Azure Pipelines and push to NuGet on build.

**Comment by philvessey** [comment]
I have now got the build working correctly so it will check any commit on a pull request but it will only push to NuGet when there is a commit to master.

**Pull request merged**
